#!/usr/bin/expect

set timeout 300
set ip "46.224.92.166"
set user "root"
set password "qR0h7fHOfn/kBwoKfOAvVg=="
set remote_path "/var/www/political_violence_tracker"

# Upload Scripts
spawn scp -o StrictHostKeyChecking=no scripts/backup_db.ts scripts/wipe_events.ts scripts/reprocess_all_raw.ts $user@$ip:$remote_path/scripts/
expect {
    "password:" { send "$password\r" }
}
expect eof

# Execute Backup
spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect {
    "password:" { send "$password\r" }
}
expect "#"
send "cd $remote_path\r"
expect "#"
send "npx tsx scripts/backup_db.ts\r"
expect "#"

# Execute Wipe
send "npx tsx scripts/wipe_events.ts\r"
expect "#"

# Exit (We will start reprocess separately to handle long running time)
send "exit\r"
expect eof
