#!/usr/bin/expect

set timeout 20
set ip "46.224.92.166"
set user "root"
set password "qR0h7fHOfn/kBwoKfOAvVg=="
set remote_path "/var/www/political_violence_tracker/scripts/run_scheduler.sh"

spawn ssh -o StrictHostKeyChecking=no $user@$ip

expect {
    "password:" { send "$password\r" }
}
expect "#"

puts "--- READING SCHEDULER SCRIPT ---"
send "cat $remote_path\r"

expect "#"
send "exit\r"
expect eof
