#!/usr/bin/expect

set timeout 300
set ip "46.224.92.166"
set user "root"
set password "qR0h7fHOfn/kBwoKfOAvVg=="
set remote_path "/var/www/political_violence_tracker"

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect {
    "password:" { send "$password\r" }
}
expect "#"

send "cd $remote_path\r"
# Start Prisma Studio on port 5555 (default) attached to PM2
send "pm2 start npx --name 'admin-db' -- prisma studio --port 5555\r"
expect "#"

# Save the list so it survives reboots
send "pm2 save\r"
expect "#"

send "exit\r"
expect eof
